# Configuration: https://dependabot.com/docs/config-file/
# Docs: https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "ğŸâ¬†ï¸"
  - package-ecosystem: "npm"
    directory: "/dumphood/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "ğŸ‘€â¬†ï¸"
  - package-ecosystem: "pip"
    directory: "/topichood/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "ğŸâ¬†ï¸"
  - package-ecosystem: "pip"
    directory: "/notionhood/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "ğŸâ¬†ï¸"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "ğŸ˜¼â¬†ï¸"
