name: Deploy to anyunderhood.github.io

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        path: project

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run build on npm setup
      working-directory: ./project
      run: |
        npm ci
        npm run build
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: static-website
        # A file, directory or wildcard pattern that describes what to upload
        path: project/dist/

    - name: Checkout ghpages repo
      uses: actions/checkout@v2
      with:
        repository: anyunderhood/anyunderhood.github.io
        path: github.io
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

    - name: Remove all files from repo
      run: git rm -r .
      working-directory: ./github.io
   
    
    - name: Copy dist to github.io repo
#       run: cp -r project/dist/ github.io
      run: cp -a project/dist/. github.io/

    - name: Commit and Push to anyunderhood.github.io
      working-directory: ./github.io # Make failable
      run: | 
        git add .
        git config --local user.email "???"
        git config --local user.name "anyunderhood"
        (git commit -m "Deploy to github.io $(date)"; git push https://$REPO_OWNER:$CUSTOM_GITHUB_TOKEN@github.com/anyunderhood/anyunderhood.github.io) || echo "Nothing to commit"
      env:
        REPO_OWNER: ${{ secrets.repository_owner }}
        CUSTOM_GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
